In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

# My data set

In [3]:
df1 = pd.read_csv('Datasets/table_for_merge.csv')

In [4]:
df1

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,month,season,carrier_name,avg_daily_delay_for_month,sum_delay_for_month,monthly_passenger_carrier,monthly_passenger_airport
0,2018-01-01,WN,WN,WN,1997.0,WN,N733SA,1997.0,13232.0,MDW,"Chicago, IL",13198.0,MCI,"Kansas City, MO",1920.0,2003.0,43.0,13.0,2016.0,2122.0,4.0,2050.0,2126.0,36.0,0.0,0.0,N,90.0,83.0,66.0,1.0,405.0,10.0,0.0,0.0,0.0,26.0,1,Winter,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
1,2018-01-01,WN,WN,WN,181.0,WN,N8633A,181.0,13232.0,MDW,"Chicago, IL",13204.0,MCO,"Orlando, FL",855.0,947.0,52.0,8.0,955.0,1306.0,5.0,1230.0,1311.0,41.0,0.0,0.0,N,155.0,144.0,131.0,1.0,990.0,11.0,0.0,0.0,0.0,30.0,1,Winter,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
2,2018-01-01,WN,WN,WN,185.0,WN,N8625A,185.0,13232.0,MDW,"Chicago, IL",13204.0,MCO,"Orlando, FL",1250.0,1307.0,17.0,12.0,1319.0,1629.0,5.0,1625.0,1634.0,9.0,0.0,0.0,N,155.0,147.0,130.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,1,Winter,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
3,2018-01-01,WN,WN,WN,403.0,WN,N564WN,403.0,13232.0,MDW,"Chicago, IL",13204.0,MCO,"Orlando, FL",1615.0,1617.0,2.0,11.0,1628.0,1935.0,5.0,1945.0,1940.0,-5.0,0.0,0.0,N,150.0,143.0,127.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,1,Winter,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
4,2018-01-01,WN,WN,WN,1229.0,WN,N8305E,1229.0,13232.0,MDW,"Chicago, IL",13204.0,MCO,"Orlando, FL",700.0,719.0,19.0,16.0,735.0,1043.0,6.0,1035.0,1049.0,14.0,0.0,0.0,N,155.0,150.0,128.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,1,Winter,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30371,2019-07-24,AA,AA_CODESHARE,AA,4807.0,PT,N624AE,4807.0,14704.0,SBY,"Salisbury, MD",14100.0,PHL,"Philadelphia, PA",1519.0,1517.0,-2.0,16.0,1533.0,1602.0,5.0,1614.0,1607.0,-7.0,0.0,0.0,N,55.0,50.0,29.0,1.0,107.0,0.0,0.0,0.0,0.0,0.0,7,Summer,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30372,2019-07-24,AA,AA_CODESHARE,AA,4808.0,PT,N649AE,4808.0,14704.0,SBY,"Salisbury, MD",14100.0,PHL,"Philadelphia, PA",1241.0,1257.0,16.0,11.0,1308.0,1332.0,7.0,1331.0,1339.0,8.0,0.0,0.0,N,50.0,42.0,24.0,1.0,107.0,0.0,0.0,0.0,0.0,0.0,7,Summer,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30373,2019-07-24,AA,AA_CODESHARE,AA,4810.0,PT,N642AE,4810.0,13139.0,LYH,"Lynchburg, VA",11057.0,CLT,"Charlotte, NC",1557.0,1725.0,88.0,15.0,1740.0,1822.0,6.0,1707.0,1828.0,81.0,0.0,0.0,N,70.0,63.0,42.0,1.0,175.0,0.0,0.0,0.0,0.0,81.0,7,Summer,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30374,2019-07-27,AS,AS_CODESHARE,AS,2067.0,QX,N446QX,2067.0,14303.0,PUW,"Pullman, WA",14747.0,SEA,"Seattle, WA",500.0,506.0,6.0,3.0,509.0,607.0,6.0,610.0,613.0,3.0,0.0,0.0,N,70.0,67.0,58.0,1.0,250.0,0.0,0.0,0.0,0.0,0.0,7,Summer,Horizon Airlines,-7.689655,-223.0,2055.0,114726.459319
30375,2019-07-27,AS,AS_CODESHARE,AS,2069.0,QX,N445QX,2069.0,11470.0,EAT,"Wenatchee, WA",14747.0,SEA,"Seattle, WA",1930.0,1943.0,13.0,6.0,1949.0,2023.0,6.0,2020.0,2029.0,9.0,0.0,0.0,N,50.0,46.0,34.0,1.0,99.0,0.0,0.0,0.0,0.0,0.0,7,Summer,Horizon Airlines,-7.689655,-223.0,2055.0,0.000000

# Hafsa's datasets

In [5]:
df2 = pd.read_csv('Datasets/df_unfiltered.csv')

In [6]:
df2

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,carrier_name,delayed,temp_night_list,temp_day_list,speed_night,speed_day,desc_night,desc_day,weather_desc
0,2018-01-01,WN,WN,WN,1997,WN,N733SA,1997,13232,MDW,"Chicago, IL",13198,MCI,"Kansas City, MO",1920,2003.0,43.0,13.0,2016.0,2122.0,4.0,2050,2126.0,36,0.0,0.0,N,90.0,83.0,66.0,1.0,405.0,10.0,0.0,0.0,0.0,26.0,Southwest Airlines,1,-17.0,-17.0,21.0,15.0,Clear,Patchy light snow,Snow
1,2018-01-01,WN,WN,WN,181,WN,N8633A,181,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",855,947.0,52.0,8.0,955.0,1306.0,5.0,1230,1311.0,41,0.0,0.0,N,155.0,144.0,131.0,1.0,990.0,11.0,0.0,0.0,0.0,30.0,Southwest Airlines,1,-17.0,-17.0,21.0,15.0,Clear,Patchy light snow,Snow
2,2018-01-01,WN,WN,WN,185,WN,N8625A,185,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",1250,1307.0,17.0,12.0,1319.0,1629.0,5.0,1625,1634.0,9,0.0,0.0,N,155.0,147.0,130.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,Southwest Airlines,1,-17.0,-17.0,21.0,15.0,Clear,Patchy light snow,Snow
3,2018-01-01,WN,WN,WN,403,WN,N564WN,403,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",1615,1617.0,2.0,11.0,1628.0,1935.0,5.0,1945,1940.0,-5,0.0,0.0,N,150.0,143.0,127.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,Southwest Airlines,0,-17.0,-17.0,21.0,15.0,Clear,Patchy light snow,Snow
4,2018-01-01,WN,WN,WN,1229,WN,N8305E,1229,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",700,719.0,19.0,16.0,735.0,1043.0,6.0,1035,1049.0,14,0.0,0.0,N,155.0,150.0,128.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,Southwest Airlines,1,-17.0,-17.0,21.0,15.0,Clear,Patchy light snow,Snow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30371,2019-07-31,DL,DL_CODESHARE,DL,3290,9E,N914XJ,3290,15412,TYS,"Knoxville, TN",12953,LGA,"New York, NY",805,749.0,-16.0,12.0,801.0,932.0,15.0,1013,947.0,-26,0.0,0.0,N,128.0,118.0,91.0,1.0,648.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30372,2019-07-31,DL,DL_CODESHARE,DL,3291,9E,N311PQ,3291,10721,BOS,"Boston, MA",13931,ORF,"Norfolk, VA",605,555.0,-10.0,26.0,621.0,734.0,5.0,750,739.0,-11,0.0,0.0,N,105.0,104.0,73.0,1.0,468.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,25.0,35.0,13.0,12.0,Clear,Sunny,Sunny
30373,2019-07-31,DL,DL_CODESHARE,DL,3292,9E,N297PQ,3292,11193,CVG,"Cincinnati, OH",11298,DFW,"Dallas/Fort Worth, TX",700,655.0,-5.0,14.0,709.0,755.0,7.0,831,802.0,-29,0.0,0.0,N,151.0,127.0,106.0,1.0,812.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30374,2019-07-31,DL,DL_CODESHARE,DL,3292,9E,N297PQ,3292,11298,DFW,"Dallas/Fort Worth, TX",11193,CVG,"Cincinnati, OH",906,858.0,-8.0,15.0,913.0,1204.0,5.0,1232,1209.0,-23,0.0,0.0,N,146.0,131.0,111.0,1.0,812.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,32.0,35.0,12.0,11.0,Clear,Sunny,Sunny
30375,2019-07-31,AA,AA,AA,1213,AA,N967NN,1213,14747,SEA,"Seattle, WA",13930,ORD,"Chicago, IL",1510,1503.0,-7.0,16.0,1519.0,2028.0,28.0,2118,2056.0,-22,0.0,0.0,N,248.0,233.0,189.0,1.0,1721.0,0.0,0.0,0.0,0.0,0.0,American Airlines,0,14.0,28.0,5.0,4.0,Clear,Sunny,Sunny

In [7]:
df3 = pd.read_csv('Datasets/df_filtered.csv')

In [8]:
df3

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,carrier_name,delayed,temp_day_list,speed_day,desc_day,weather_desc,day_of_week
0,2018-01-01,WN,WN,WN,1997,WN,N733SA,1997,13232,MDW,"Chicago, IL",13198,MCI,"Kansas City, MO",1920,2003.0,43.0,13.0,2016.0,2122.0,4.0,2050,2126.0,36,0.0,0.0,N,90.0,83.0,66.0,1.0,405.0,10.0,0.0,0.0,0.0,26.0,Southwest Airlines,1,-17.0,15.0,Patchy light snow,Snow,Monday
1,2018-01-01,WN,WN,WN,181,WN,N8633A,181,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",855,947.0,52.0,8.0,955.0,1306.0,5.0,1230,1311.0,41,0.0,0.0,N,155.0,144.0,131.0,1.0,990.0,11.0,0.0,0.0,0.0,30.0,Southwest Airlines,1,-17.0,15.0,Patchy light snow,Snow,Monday
2,2018-01-01,WN,WN,WN,185,WN,N8625A,185,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",1250,1307.0,17.0,12.0,1319.0,1629.0,5.0,1625,1634.0,9,0.0,0.0,N,155.0,147.0,130.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,Southwest Airlines,1,-17.0,15.0,Patchy light snow,Snow,Monday
3,2018-01-01,WN,WN,WN,403,WN,N564WN,403,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",1615,1617.0,2.0,11.0,1628.0,1935.0,5.0,1945,1940.0,-5,0.0,0.0,N,150.0,143.0,127.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,Southwest Airlines,0,-17.0,15.0,Patchy light snow,Snow,Monday
4,2018-01-01,WN,WN,WN,1229,WN,N8305E,1229,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",700,719.0,19.0,16.0,735.0,1043.0,6.0,1035,1049.0,14,0.0,0.0,N,155.0,150.0,128.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,Southwest Airlines,1,-17.0,15.0,Patchy light snow,Snow,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20569,2019-07-31,DL,DL_CODESHARE,DL,3287,9E,N936XJ,3287,11433,DTW,"Detroit, MI",11193,CVG,"Cincinnati, OH",1605,1559.0,-6.0,12.0,1611.0,1656.0,4.0,1725,1700.0,-25,0.0,0.0,N,80.0,61.0,45.0,1.0,229.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,24.0,14.0,Partly cloudy,Cloudy,Wednesday
20570,2019-07-31,DL,DL_CODESHARE,DL,3288,9E,N8683B,3288,10397,ATL,"Atlanta, GA",10990,CHO,"Charlottesville, VA",2123,2119.0,-4.0,35.0,2154.0,2301.0,3.0,2300,2304.0,4,0.0,0.0,N,97.0,105.0,67.0,1.0,457.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,1,32.0,5.0,Sunny,Sunny,Wednesday
20571,2019-07-31,DL,DL_CODESHARE,DL,3291,9E,N311PQ,3291,10721,BOS,"Boston, MA",13931,ORF,"Norfolk, VA",605,555.0,-10.0,26.0,621.0,734.0,5.0,750,739.0,-11,0.0,0.0,N,105.0,104.0,73.0,1.0,468.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,35.0,12.0,Sunny,Sunny,Wednesday
20572,2019-07-31,DL,DL_CODESHARE,DL,3292,9E,N297PQ,3292,11298,DFW,"Dallas/Fort Worth, TX",11193,CVG,"Cincinnati, OH",906,858.0,-8.0,15.0,913.0,1204.0,5.0,1232,1209.0,-23,0.0,0.0,N,146.0,131.0,111.0,1.0,812.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,35.0,11.0,Sunny,Sunny,Wednesday
20573,2019-07-31,AA,AA,AA,1213,AA,N967NN,1213,14747,SEA,"Seattle, WA",13930,ORD,"Chicago, IL",1510,1503.0,-7.0,16.0,1519.0,2028.0,28.0,2118,2056.0,-22,0.0,0.0,N,248.0,233.0,189.0,1.0,1721.0,0.0,0.0,0.0,0.0,0.0,American Airlines,0,28.0,4.0,Sunny,Sunny,Wednesday

# Merging

In [8]:
# hafsa said to use this after merge. Seems like I might need to change it a bit
df.drop(['temp_night_list', 'speed_night', 'desc_night'], axis=1, inplace=True)
df['temp_day_list'] = df['temp_day_list'].fillna('none')
df['speed_day'] = df['speed_day'].fillna('none')
df['desc_day'] = df['desc_day'].fillna('none')
for index, row in df.iterrows():   # drop rows with no weather data
    if row['temp_day_list'] == 'none':
        df.drop(index=index, inplace=True)
for index, row in df.iterrows():   # drop rows with no weather data
    if row['speed_day'] == 'none':
        df.drop(index=index, inplace=True)
for index, row in df.iterrows():   # drop rows with no weather data
    if row['desc_day'] == 'none':
        df.drop(index=index, inplace=True)
df['fl_date'] = pd.to_datetime(df['fl_date'])
df['day_of_week'] = df['fl_date'].dt.day_name()

NameError: name 'df' is not defined

How to proceed to merge..might only keep relevant features from my table and add hafsa's

In [10]:
df1

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,month,season,carrier_name,avg_daily_delay_for_month,sum_delay_for_month,monthly_passenger_carrier,monthly_passenger_airport
0,2018-01-01,WN,WN,WN,1997.0,WN,N733SA,1997.0,13232.0,MDW,"Chicago, IL",13198.0,MCI,"Kansas City, MO",1920.0,2003.0,43.0,13.0,2016.0,2122.0,4.0,2050.0,2126.0,36.0,0.0,0.0,N,90.0,83.0,66.0,1.0,405.0,10.0,0.0,0.0,0.0,26.0,1,Winter,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
1,2018-01-01,WN,WN,WN,181.0,WN,N8633A,181.0,13232.0,MDW,"Chicago, IL",13204.0,MCO,"Orlando, FL",855.0,947.0,52.0,8.0,955.0,1306.0,5.0,1230.0,1311.0,41.0,0.0,0.0,N,155.0,144.0,131.0,1.0,990.0,11.0,0.0,0.0,0.0,30.0,1,Winter,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
2,2018-01-01,WN,WN,WN,185.0,WN,N8625A,185.0,13232.0,MDW,"Chicago, IL",13204.0,MCO,"Orlando, FL",1250.0,1307.0,17.0,12.0,1319.0,1629.0,5.0,1625.0,1634.0,9.0,0.0,0.0,N,155.0,147.0,130.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,1,Winter,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
3,2018-01-01,WN,WN,WN,403.0,WN,N564WN,403.0,13232.0,MDW,"Chicago, IL",13204.0,MCO,"Orlando, FL",1615.0,1617.0,2.0,11.0,1628.0,1935.0,5.0,1945.0,1940.0,-5.0,0.0,0.0,N,150.0,143.0,127.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,1,Winter,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
4,2018-01-01,WN,WN,WN,1229.0,WN,N8305E,1229.0,13232.0,MDW,"Chicago, IL",13204.0,MCO,"Orlando, FL",700.0,719.0,19.0,16.0,735.0,1043.0,6.0,1035.0,1049.0,14.0,0.0,0.0,N,155.0,150.0,128.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,1,Winter,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30371,2019-07-24,AA,AA_CODESHARE,AA,4807.0,PT,N624AE,4807.0,14704.0,SBY,"Salisbury, MD",14100.0,PHL,"Philadelphia, PA",1519.0,1517.0,-2.0,16.0,1533.0,1602.0,5.0,1614.0,1607.0,-7.0,0.0,0.0,N,55.0,50.0,29.0,1.0,107.0,0.0,0.0,0.0,0.0,0.0,7,Summer,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30372,2019-07-24,AA,AA_CODESHARE,AA,4808.0,PT,N649AE,4808.0,14704.0,SBY,"Salisbury, MD",14100.0,PHL,"Philadelphia, PA",1241.0,1257.0,16.0,11.0,1308.0,1332.0,7.0,1331.0,1339.0,8.0,0.0,0.0,N,50.0,42.0,24.0,1.0,107.0,0.0,0.0,0.0,0.0,0.0,7,Summer,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30373,2019-07-24,AA,AA_CODESHARE,AA,4810.0,PT,N642AE,4810.0,13139.0,LYH,"Lynchburg, VA",11057.0,CLT,"Charlotte, NC",1557.0,1725.0,88.0,15.0,1740.0,1822.0,6.0,1707.0,1828.0,81.0,0.0,0.0,N,70.0,63.0,42.0,1.0,175.0,0.0,0.0,0.0,0.0,81.0,7,Summer,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30374,2019-07-27,AS,AS_CODESHARE,AS,2067.0,QX,N446QX,2067.0,14303.0,PUW,"Pullman, WA",14747.0,SEA,"Seattle, WA",500.0,506.0,6.0,3.0,509.0,607.0,6.0,610.0,613.0,3.0,0.0,0.0,N,70.0,67.0,58.0,1.0,250.0,0.0,0.0,0.0,0.0,0.0,7,Summer,Horizon Airlines,-7.689655,-223.0,2055.0,114726.459319
30375,2019-07-27,AS,AS_CODESHARE,AS,2069.0,QX,N445QX,2069.0,11470.0,EAT,"Wenatchee, WA",14747.0,SEA,"Seattle, WA",1930.0,1943.0,13.0,6.0,1949.0,2023.0,6.0,2020.0,2029.0,9.0,0.0,0.0,N,50.0,46.0,34.0,1.0,99.0,0.0,0.0,0.0,0.0,0.0,7,Summer,Horizon Airlines,-7.689655,-223.0,2055.0,0.000000

In [11]:
features_df1 = ['fl_date', 'op_unique_carrier', 'origin_city_name', 'arr_delay', 'month', 'carrier_name', 'avg_daily_delay_for_month',
           'sum_delay_for_month', 'monthly_passenger_carrier', 'monthly_passenger_airport']

In [12]:
part_1 = df1[features_df1]
part_1

,fl_date,op_unique_carrier,origin_city_name,arr_delay,month,carrier_name,avg_daily_delay_for_month,sum_delay_for_month,monthly_passenger_carrier,monthly_passenger_airport
0,2018-01-01,WN,"Chicago, IL",36.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
1,2018-01-01,WN,"Chicago, IL",41.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
2,2018-01-01,WN,"Chicago, IL",9.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
3,2018-01-01,WN,"Chicago, IL",-5.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
4,2018-01-01,WN,"Chicago, IL",14.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
...,...,...,...,...,...,...,...,...,...,...
30371,2019-07-24,PT,"Salisbury, MD",-7.0,7,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30372,2019-07-24,PT,"Salisbury, MD",8.0,7,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30373,2019-07-24,PT,"Lynchburg, VA",81.0,7,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30374,2019-07-27,QX,"Pullman, WA",3.0,7,Horizon Airlines,-7.689655,-223.0,2055.0,114726.459319
30375,2019-07-27,QX,"Wenatchee, WA",9.0,7,Horizon Airlines,-7.689655,-223.0,2055.0,0.000000

In [39]:
df2

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,carrier_name,delayed,temp_night_list,temp_day_list,speed_night,speed_day,desc_night,desc_day,weather_desc
0,2018-01-01,WN,WN,WN,1997,WN,N733SA,1997,13232,MDW,"Chicago, IL",13198,MCI,"Kansas City, MO",1920,2003.0,43.0,13.0,2016.0,2122.0,4.0,2050,2126.0,36,0.0,0.0,N,90.0,83.0,66.0,1.0,405.0,10.0,0.0,0.0,0.0,26.0,Southwest Airlines,1,-17.0,-17.0,21.0,15.0,Clear,Patchy light snow,Snow
1,2018-01-01,WN,WN,WN,181,WN,N8633A,181,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",855,947.0,52.0,8.0,955.0,1306.0,5.0,1230,1311.0,41,0.0,0.0,N,155.0,144.0,131.0,1.0,990.0,11.0,0.0,0.0,0.0,30.0,Southwest Airlines,1,-17.0,-17.0,21.0,15.0,Clear,Patchy light snow,Snow
2,2018-01-01,WN,WN,WN,185,WN,N8625A,185,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",1250,1307.0,17.0,12.0,1319.0,1629.0,5.0,1625,1634.0,9,0.0,0.0,N,155.0,147.0,130.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,Southwest Airlines,1,-17.0,-17.0,21.0,15.0,Clear,Patchy light snow,Snow
3,2018-01-01,WN,WN,WN,403,WN,N564WN,403,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",1615,1617.0,2.0,11.0,1628.0,1935.0,5.0,1945,1940.0,-5,0.0,0.0,N,150.0,143.0,127.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,Southwest Airlines,0,-17.0,-17.0,21.0,15.0,Clear,Patchy light snow,Snow
4,2018-01-01,WN,WN,WN,1229,WN,N8305E,1229,13232,MDW,"Chicago, IL",13204,MCO,"Orlando, FL",700,719.0,19.0,16.0,735.0,1043.0,6.0,1035,1049.0,14,0.0,0.0,N,155.0,150.0,128.0,1.0,990.0,0.0,0.0,0.0,0.0,0.0,Southwest Airlines,1,-17.0,-17.0,21.0,15.0,Clear,Patchy light snow,Snow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30371,2019-07-31,DL,DL_CODESHARE,DL,3290,9E,N914XJ,3290,15412,TYS,"Knoxville, TN",12953,LGA,"New York, NY",805,749.0,-16.0,12.0,801.0,932.0,15.0,1013,947.0,-26,0.0,0.0,N,128.0,118.0,91.0,1.0,648.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30372,2019-07-31,DL,DL_CODESHARE,DL,3291,9E,N311PQ,3291,10721,BOS,"Boston, MA",13931,ORF,"Norfolk, VA",605,555.0,-10.0,26.0,621.0,734.0,5.0,750,739.0,-11,0.0,0.0,N,105.0,104.0,73.0,1.0,468.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,25.0,35.0,13.0,12.0,Clear,Sunny,Sunny
30373,2019-07-31,DL,DL_CODESHARE,DL,3292,9E,N297PQ,3292,11193,CVG,"Cincinnati, OH",11298,DFW,"Dallas/Fort Worth, TX",700,655.0,-5.0,14.0,709.0,755.0,7.0,831,802.0,-29,0.0,0.0,N,151.0,127.0,106.0,1.0,812.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30374,2019-07-31,DL,DL_CODESHARE,DL,3292,9E,N297PQ,3292,11298,DFW,"Dallas/Fort Worth, TX",11193,CVG,"Cincinnati, OH",906,858.0,-8.0,15.0,913.0,1204.0,5.0,1232,1209.0,-23,0.0,0.0,N,146.0,131.0,111.0,1.0,812.0,0.0,0.0,0.0,0.0,0.0,Endeavor Air,0,32.0,35.0,12.0,11.0,Clear,Sunny,Sunny
30375,2019-07-31,AA,AA,AA,1213,AA,N967NN,1213,14747,SEA,"Seattle, WA",13930,ORD,"Chicago, IL",1510,1503.0,-7.0,16.0,1519.0,2028.0,28.0,2118,2056.0,-22,0.0,0.0,N,248.0,233.0,189.0,1.0,1721.0,0.0,0.0,0.0,0.0,0.0,American Airlines,0,14.0,28.0,5.0,4.0,Clear,Sunny,Sunny

In [51]:
features_df2 = ['fl_date', 'origin_city_name','temp_day_list', 'speed_day', 'desc_day', 'weather_desc']

In [56]:
part_2 = df2[features_df2]
part_2

,fl_date,origin_city_name,temp_day_list,speed_day,desc_day,weather_desc
0,2018-01-01,"Chicago, IL",-17.0,15.0,Patchy light snow,Snow
1,2018-01-01,"Chicago, IL",-17.0,15.0,Patchy light snow,Snow
2,2018-01-01,"Chicago, IL",-17.0,15.0,Patchy light snow,Snow
3,2018-01-01,"Chicago, IL",-17.0,15.0,Patchy light snow,Snow
4,2018-01-01,"Chicago, IL",-17.0,15.0,Patchy light snow,Snow
...,...,...,...,...,...,...
30371,2019-07-31,"Knoxville, TN",NaN,NaN,NaN,NaN
30372,2019-07-31,"Boston, MA",35.0,12.0,Sunny,Sunny
30373,2019-07-31,"Cincinnati, OH",NaN,NaN,NaN,NaN
30374,2019-07-31,"Dallas/Fort Worth, TX",35.0,11.0,Sunny,Sunny
30375,2019-07-31,"Seattle, WA",28.0,4.0,Sunny,Sunny

# Merge
something just isn't working. The merge is not happening correctly, the dataset seems to concatenate instead of merging

# Transform
get table ready for modeling

In [13]:
part_1

,fl_date,op_unique_carrier,origin_city_name,arr_delay,month,carrier_name,avg_daily_delay_for_month,sum_delay_for_month,monthly_passenger_carrier,monthly_passenger_airport
0,2018-01-01,WN,"Chicago, IL",36.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
1,2018-01-01,WN,"Chicago, IL",41.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
2,2018-01-01,WN,"Chicago, IL",9.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
3,2018-01-01,WN,"Chicago, IL",-5.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
4,2018-01-01,WN,"Chicago, IL",14.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
...,...,...,...,...,...,...,...,...,...,...
30371,2019-07-24,PT,"Salisbury, MD",-7.0,7,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30372,2019-07-24,PT,"Salisbury, MD",8.0,7,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30373,2019-07-24,PT,"Lynchburg, VA",81.0,7,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30374,2019-07-27,QX,"Pullman, WA",3.0,7,Horizon Airlines,-7.689655,-223.0,2055.0,114726.459319
30375,2019-07-27,QX,"Wenatchee, WA",9.0,7,Horizon Airlines,-7.689655,-223.0,2055.0,0.000000

need to hot encode the city, carrier. Won't need the first 2 columns

In [14]:
part_1 = part_1.drop(columns=['fl_date', 'op_unique_carrier'], axis=1)

In [15]:
part_1

,origin_city_name,arr_delay,month,carrier_name,avg_daily_delay_for_month,sum_delay_for_month,monthly_passenger_carrier,monthly_passenger_airport
0,"Chicago, IL",36.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
1,"Chicago, IL",41.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
2,"Chicago, IL",9.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
3,"Chicago, IL",-5.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
4,"Chicago, IL",14.0,1,Southwest Airlines,0.659208,383.0,345355.0,158843.000000
...,...,...,...,...,...,...,...,...
30371,"Salisbury, MD",-7.0,7,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30372,"Salisbury, MD",8.0,7,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30373,"Lynchburg, VA",81.0,7,Piedmont Airlines,-4.250000,-119.0,908.0,114726.459319
30374,"Pullman, WA",3.0,7,Horizon Airlines,-7.689655,-223.0,2055.0,114726.459319
30375,"Wenatchee, WA",9.0,7,Horizon Airlines,-7.689655,-223.0,2055.0,0.000000

In [228]:
part_1.to_csv(r'./table_for_model.csv', index = False)

# one hot encoder

In [86]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = part_1['carrier_name']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['Southwest Airlines' 'Southwest Airlines' 'Southwest Airlines' ...
 'Piedmont Airlines' 'Horizon Airlines' 'Horizon Airlines']
[22 22 22 ... 19 13 13]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['Southwest Airlines']

# Train test split

In [103]:
# the hot encoder part seems to have too many steps, will come back to it
X = part_1.loc[:, ['origin_city_name', 'month', 'carrier_name', 'avg_daily_delay_for_month', 'sum_delay_for_month',
              'monthly_passenger_carrier', 'monthly_passenger_airport']]
y = part_1.arr_delay

In [108]:
print(X.shape)
print(y.shape)

(30376, 7)
(30376,)

In [109]:
X_num = part_1.loc[:, ['month', 'avg_daily_delay_for_month', 'sum_delay_for_month',
              'monthly_passenger_carrier', 'monthly_passenger_airport']]

In [111]:
X_num.shape

(30376, 5)

In [106]:
from sklearn.model_selection import train_test_split

In [112]:
X_train, X_test, y_train, y_test = train_test_split(X_num, y, test_size = 0.3, random_state=5)

In [114]:
import sklearn.linear_model as linear_model
from sklearn.preprocessing import StandardScaler

In [148]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [199]:
X_train_scaled

array([[-1.04485906, -0.76553072, -0.78071204, -0.83386666,  1.39754554],
       [-1.04485906, -0.82068861, -1.15090575,  0.12830004, -0.27740173],
       [-1.63978296, -2.03351728, -0.81929719, -1.01945098, -0.45319338],
       ...,
       [ 0.73991265,  0.37644919, -0.5083792 , -0.88838294, -0.2000682 ],
       [ 1.6322985 , -0.39102721, -0.55647084, -0.94565834,  1.1227285 ],
       [ 0.44245069, -0.04901249,  0.80910778,  0.29646618,  1.10419361]])

# Basic model

In [155]:
lasso = linear_model.Lasso()

In [204]:
lasso.fit(X_train_scaled, y_train)

Lasso()

In [205]:
y_pred = lasso.predict(X_test_scaled)
y_pred

array([13.85250277,  1.20139706,  4.01951115, ..., -1.12556735,
       28.58457269, -3.10252348])

In [206]:
y_test

13962      7.0
26642    -11.0
3727     -27.0
15808    199.0
13379    -10.0
         ...
7777     -21.0
19220      2.0
15778    -20.0
19150    112.0
20380     -9.0
Name: arr_delay, Length: 9113, dtype: float64

In [140]:
# evaluation
from sklearn.metrics import mean_absolute_error

In [207]:
MAE_lasso = mean_absolute_error(y_test, y_pred)
print(MAE_lasso)

23.970211366940994

In [145]:
from sklearn.metrics import mean_squared_error

In [208]:
MSE_lasso = mean_squared_error(y_test, y_pred)
print(MSE_lasso)

2263.8919093898785

In [142]:
from sklearn.metrics import r2_score

In [209]:
r2_score_lasso = r2_score(y_test, y_pred)
print(r2_score_lasso)

0.025688487094507106

# Grid Search

In [151]:
from sklearn.model_selection import GridSearchCV

In [327]:
param_grid1 = {
    'alpha': [0.001, 0.01, 0.1, 0.25, 0.5, 0.75, 1, 3, 5]
}

param_grid2 = {
    'alpha': [0.001, 0.01, 0.1, 0.25, 0.5, 0.75, 1, 3, 5],
    'l1_ratio': [0, 0.25, 0.5, 0.75, 1]
}

lasso = linear_model.Lasso()
ridge = linear_model.Ridge()
elastic = linear_model.ElasticNet()

## Grid search lasso

In [290]:
grid = GridSearchCV(estimator=lasso, param_grid=param_grid1, scoring='r2', cv=100, verbose=1, n_jobs=-1)

In [298]:
grid_result = grid.fit(X_train_scaled, y_train)

Fitting 100 folds for each of 9 candidates, totalling 900 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done 900 out of 900 | elapsed:    1.5s finished

In [299]:
print(grid_result.best_score_)
print(grid_result.best_params_)

0.03227166678685861
{'alpha': 1}

In [300]:
y_pred_g1 = grid.predict(X_test_scaled)

In [301]:
y_pred_g1

array([13.85250277,  1.20139706,  4.01951115, ..., -1.12556735,
       28.58457269, -3.10252348])

In [302]:
g1_MSE = mean_squared_error(y_test, y_pred_g1)
print(g1_MSE)

2263.8919093898785

In [303]:
g1_MAE = mean_absolute_error(y_test, y_pred_g1)
print(g1_MAE)

23.970211366940994

In [305]:
r2_score_g1 = r2_score(y_test, y_pred_g1)
print(r2_score_g1)

0.025688487094507106

## Grid search ridge

In [306]:
grid2 =  GridSearchCV(estimator=ridge, param_grid=param_grid1, scoring='r2', verbose=1, n_jobs=-1)

In [307]:
grid2_result = grid2.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  45 out of  45 | elapsed:   24.1s finished

In [308]:
print(grid2_result.best_score_)
print(grid2_result.best_params_)

0.039905522253102996
{'alpha': 5}

In [309]:
y_pred_g2 = grid2.predict(X_test_scaled)

In [312]:
g2_MSE = mean_squared_error(y_test, y_pred_g2)
g2_MSE

2265.8796081436567

## Grid search elasticnet

In [322]:
grid3 = GridSearchCV(estimator=elastic, param_grid=param_grid2, scoring='r2', cv=50, verbose=1, n_jobs=-1)

In [328]:
grid3_result = grid3.fit(X_train_scaled, y_train)

Fitting 50 folds for each of 35 candidates, totalling 1750 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    4.5s
[Parallel(n_jobs=-1)]: Done 766 tasks      | elapsed:   13.2s
[Parallel(n_jobs=-1)]: Done 1662 tasks      | elapsed:   25.4s
[Parallel(n_jobs=-1)]: Done 1750 out of 1750 | elapsed:   27.9s finished

In [329]:
print(grid3_result.best_score_)
print(grid3_result.best_params_) # same results as lasso

0.037199269884730476
{'alpha': 0.5, 'l1_ratio': 1}

In [330]:
y_pred_g3 = grid3.predict(X_test_scaled)

In [331]:
g3_MSE = mean_squared_error(y_test, y_pred_g3)
g3_MSE

2264.373329246114